#!/bin/sh -e

cp data/ldap.ini ../config/
cp data/database.ini ../config/

./start_ldap

trap "./stop_ldap" INT HUP QUIT EXIT ERR

case "$1" in
	'')
		testfile="alltests.php"
		;;
	
	unit|func)
		testfile="$1tests.php"
		;;
	
	*)
		testfile="functests.php $*"
		;;
esac

TFILE=$(mktemp)

php4 -Cq ./$testfile >> $TFILE || true


rm -f ../config/ldap.ini ../config/database.ini

if [ $( wc -l "$TFILE" | cut -d ' ' -f 1 ) -gt 20 ]; then
	less $TFILE
else
	cat $TFILE
fi

rm $TFILE
